/* FeeFlow offline engine: replaces server.js. All data lives on this device (IndexedDB). */
(function(G){
const T=['users','institutes','students','fees','fee_types','sfi','alloc','activity','subs','otp'];
let D={},ready,session=null;const uid=()=>crypto.randomUUID?crypto.randomUUID():'id'+Date.now()+Math.random().toString(36).slice(2);
const now=()=>new Date().toISOString(),num=x=>Number(x||0),day=iso=>{const d=new Date(iso);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const PLANS={trial:['Free Trial',0,1],monthly:['Monthly',499,1],yearly:['Yearly',4999,1],fiveyear:['5 Year',17999,5],lifetime:['Lifetime',29999,5]};
const HEADS=['Tuition Fee','Admission Fee','Travel Fee','Exam Fee','Other Fee'];
async function hash(p){try{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('ff|'+p));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch(e){let h=5381;for(const c of 'ff|'+p)h=(h*33^c.charCodeAt(0))>>>0;return 'x'+h}}
function idb(){return new Promise((res,rej)=>{const r=indexedDB.open('feeflow',1);r.onupgradeneeded=()=>r.result.createObjectStore('kv');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function load(){const db=await idb();D=await new Promise(res=>{const q=db.transaction('kv').objectStore('kv').get('db');q.onsuccess=()=>res(q.result||{});q.onerror=()=>res({})});T.forEach(t=>D[t]=D[t]||[]);
 if(!D.users.length){const id=uid();D.users.push({id,owner_id:id,phone:'9999999999',email:'admin@demo.local',name:'Demo Owner',password_hash:await hash('Admin@123'),role:'SUPER_ADMIN',active:1,created_at:now()});D.subs.push({id:uid(),owner_id:id,plan_id:'lifetime',start_at:now(),end_at:null,active:1});newInst(id,'Demo Institute');await save()}
 try{const s=JSON.parse(localStorage.getItem('ff_session')||'null');session=s&&D.users.find(u=>u.id===s.id)?s:null}catch(e){}}
let t;function save(){clearTimeout(t);return new Promise(async res=>{const db=await idb();const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(D,'db');tx.oncomplete=()=>res()})}
function newInst(owner,name,b={}){const id=uid();D.institutes.push({id,owner_id:owner,name,logo_url:b.logo_url||'',address:b.address||'',phone:b.phone||'',email:b.email||'',branding:b.branding?1:0,created_at:now()});HEADS.forEach(n=>D.fee_types.push({id:uid(),institute_id:id,name:n,default_amount:0,active:1,created_at:now()}));return id}
const E=(m,s=400)=>{throw{status:s,message:m}};
const owner=()=>session.ownerId;
const inst=id=>D.institutes.find(i=>i.id===id&&i.owner_id===owner());
const ftOK=id=>{const f=D.fee_types.find(x=>x.id===id);return f&&inst(f.institute_id)?f:null};
const stu=id=>{const s=D.students.find(x=>x.id===id);const i=s&&inst(s.institute_id);return i?{...s,institute_name:i.name}:null};
const log=(a,m='')=>D.activity.push({id:uid(),user_id:session.id,action:a,meta:m,created_at:now()});
function summary(sid){const s=D.students.find(x=>x.id===sid);if(!s)return null;const fids=new Set(D.fees.filter(f=>f.student_id===sid).map(f=>f.id));
 return D.fee_types.filter(f=>f.institute_id===s.institute_id&&f.active).sort((a,b)=>a.name.localeCompare(b.name)).map(f=>{const a=num((D.sfi.find(x=>x.student_id===sid&&x.fee_type_id===f.id)||{}).assigned_amount);const paid=D.alloc.filter(x=>x.fee_type_id===f.id&&fids.has(x.fee_id)).reduce((t,x)=>t+num(x.amount),0);return{fee_type_id:f.id,fee_type_name:f.name,assigned_amount:a,paid,balance:Math.max(0,a-paid)}})}
const sum=(r,k)=>r.reduce((t,x)=>t+num(x[k]),0);
function setItems(sid,instId,items){D.sfi=D.sfi.filter(x=>x.student_id!==sid);let tot=0;for(const x of items||[]){const ft=ftOK(x.fee_type_id);if(!ft||ft.institute_id!==instId)E('Invalid fee type');const a=Math.max(0,num(x.amount));if(a>0){D.sfi.push({id:uid(),student_id:sid,fee_type_id:x.fee_type_id,assigned_amount:a});tot+=a}}return tot}
const withAlloc=f=>({...f,allocations:D.alloc.filter(a=>a.fee_id===f.id).map(a=>({amount:a.amount,fee_type_id:a.fee_type_id,fee_type_name:D.fee_types.find(x=>x.id===a.fee_type_id).name})).sort((a,b)=>a.fee_type_name.localeCompare(b.fee_type_name))});
const R=[];const route=(m,p,fn,pub)=>R.push([m,new RegExp('^'+p.replace(/:\w+/g,'([^/]+)')+'$'),fn,pub]);
const tokenUser=u=>{session={id:u.id,ownerId:u.owner_id||u.id,role:u.role};localStorage.setItem('ff_session',JSON.stringify(session));return{ok:true,user:{id:u.id,name:u.name,role:u.role}}};
route('POST','/api/auth/request-otp',async b=>{const p=String(b.phone||'').replace(/\D/g,'');if(p.length<10)E('Valid mobile number required');const c=String(Math.floor(1e5+Math.random()*9e5));D.otp.push({phone:p,code:c,exp:Date.now()+3e5,used:0});return{ok:true,message:'Offline OTP: '+c}},1);
route('POST','/api/auth/verify-otp',async b=>{const p=String(b.phone||'').replace(/\D/g,'');const o=D.otp.find(x=>x.phone===p&&x.code===String(b.code||'')&&!x.used&&x.exp>Date.now());if(!o)E('Invalid or expired OTP');o.used=1;let u=D.users.find(x=>x.phone===p);if(!u){const id=uid();u={id,owner_id:id,phone:p,email:null,name:'New Owner',password_hash:await hash('ChangeMe@123'),role:'OWNER',active:1,created_at:now()};D.users.push(u);D.subs.push({id:uid(),owner_id:id,plan_id:'trial',start_at:now(),end_at:new Date(Date.now()+14*864e5).toISOString(),active:1});newInst(id,'My Institute')}return tokenUser(u)},1);
route('POST','/api/auth/login',async b=>{const p=String(b.phone||'').replace(/\D/g,'');const u=D.users.find(x=>x.phone===p&&x.active);if(!u||u.password_hash!==await hash(String(b.password||'')))E('Wrong mobile or password',401);return tokenUser(u)},1);
route('POST','/api/auth/password',async b=>{if(String(b.password||'').length<8)E('Password must be at least 8 characters');D.users.find(u=>u.id===session.id).password_hash=await hash(b.password);return{ok:true}});
route('POST','/api/auth/logout',()=>{session=null;localStorage.removeItem('ff_session');return{ok:true}},1);
route('GET','/api/me',()=>{const u=D.users.find(x=>x.id===session.id);const{password_hash,...user}=u;const s=D.subs.filter(x=>x.owner_id===owner()&&x.active).sort((a,b)=>b.start_at.localeCompare(a.start_at))[0];const p=s&&PLANS[s.plan_id];return{user,subscription:s?{...s,plan_name:p[0],price:p[1],max_institutes:p[2]}:undefined}});
route('GET','/api/institutes',()=>D.institutes.filter(i=>i.owner_id===owner()).sort((a,b)=>b.created_at.localeCompare(a.created_at)));
route('POST','/api/institutes',b=>{const s=D.subs.filter(x=>x.owner_id===owner()&&x.active)[0];const mx=s&&PLANS[s.plan_id][2];if(mx&&D.institutes.filter(i=>i.owner_id===owner()).length>=mx)E(`Your plan allows ${mx} institute(s).`,403);if(!b.name)E('Institute name required');const id=newInst(owner(),b.name,b);log('INSTITUTE_CREATE',id);return{ok:true,id}});
route('PUT','/api/institutes/:id',(b,id)=>{const i=inst(id);if(!i)E('Not found',404);Object.assign(i,{name:b.name,logo_url:b.logo_url||'',address:b.address||'',phone:b.phone||'',email:b.email||'',branding:b.branding?1:0});return{ok:true}});
route('GET','/api/fee-types',(b,q)=>{if(!inst(q.instituteId))E('Institute not found',404);return D.fee_types.filter(f=>f.institute_id===q.instituteId&&f.active).sort((a,b)=>a.name.localeCompare(b.name))});
route('POST','/api/fee-types',b=>{if(!inst(b.instituteId))E('Institute not found',404);const n=String(b.name||'').trim();if(!n)E('Fee type name required');if(D.fee_types.some(f=>f.institute_id===b.instituteId&&f.name===n))E('This fee type already exists');const id=uid();D.fee_types.push({id,institute_id:b.instituteId,name:n,default_amount:num(b.default_amount),active:1,created_at:now()});log('FEE_TYPE_CREATE',id+':'+n);return{ok:true,id}});
route('PUT','/api/fee-types/:id',(b,id)=>{const f=ftOK(id);if(!f)E('Not found',404);f.name=String(b.name||'').trim();f.default_amount=num(b.default_amount);return{ok:true}});
route('GET','/api/students',(b,q)=>{if(!inst(q.instituteId))E('Institute not found',404);return D.students.filter(s=>s.institute_id===q.instituteId).sort((a,b)=>a.name.localeCompare(b.name)).map(s=>{const it=summary(s.id),tf=sum(it,'assigned_amount'),p=sum(it,'paid');return{...s,fee_items:it,total_fee:tf,paid:p,balance:Math.max(0,tf-p)}})});
route('GET','/api/students/:id/fee-structure',(b,id)=>{const s=stu(id);if(!s)E('Student not found',404);return{student:s,items:summary(id)}});
route('POST','/api/students',b=>{if(!inst(b.instituteId)||!b.name)E('Institute and student name required');const id=uid(),bak=JSON.stringify(D);try{D.students.push({id,institute_id:b.instituteId,admission_no:b.admission_no||'',name:b.name,guardian:b.guardian||'',phone:b.phone||'',class_name:b.class_name||'',section:b.section||'',total_fee:0,active:1,created_at:now()});D.students.at(-1).total_fee=setItems(id,b.instituteId,b.fee_items)}catch(e){D=JSON.parse(bak);throw e}log('STUDENT_CREATE',id);return{ok:true,id}});
route('PUT','/api/students/:id',(b,id)=>{const s0=stu(id);if(!s0)E('Not found',404);const s=D.students.find(x=>x.id===id),bak=JSON.stringify(D);try{Object.assign(s,{admission_no:b.admission_no||'',name:b.name,guardian:b.guardian||'',phone:b.phone||'',class_name:b.class_name||'',section:b.section||'',active:b.active===false?0:1});s.total_fee=setItems(id,s.institute_id,b.fee_items)}catch(e){D=JSON.parse(bak);throw e}log('STUDENT_UPDATE',id);return{ok:true}});
route('POST','/api/fees',b=>{const s=stu(b.studentId);if(!s)E('Valid student required');const cl=(Array.isArray(b.allocations)?b.allocations:[]).map(x=>({fee_type_id:x.fee_type_id,amount:num(x.amount)})).filter(x=>x.amount>0);if(!cl.length)E('Enter at least one fee type amount');const tot=sum(cl,'amount');if(Math.abs(tot-num(b.amount||tot))>0.005)E('Allocation total must equal received amount');const by=new Map(summary(s.id).map(x=>[x.fee_type_id,x]));for(const x of cl){const ft=ftOK(x.fee_type_id);if(!ft||ft.institute_id!==s.institute_id)E('Invalid fee type');const r=by.get(x.fee_type_id);if(!r)E('This fee is not assigned to the student');if(x.amount>r.balance+0.005)E(`${r.fee_type_name} balance is only ₹${r.balance}`)}
 const rn=Math.max(0,...D.fees.filter(f=>f.institute_id===s.institute_id).map(f=>f.receipt_no))+1,id=uid();D.fees.push({id,institute_id:s.institute_id,student_id:s.id,receipt_no:rn,amount:tot,payment_mode:b.payment_mode||'Cash',remarks:b.remarks||'',received_by:session.id,received_at:now()});cl.forEach(x=>D.alloc.push({id:uid(),fee_id:id,fee_type_id:x.fee_type_id,amount:x.amount}));log('FEE_RECEIVED',id+':'+rn);return{ok:true,id,receipt_no:rn}});
route('GET','/api/fees',(b,q)=>{if(!inst(q.instituteId))E('Institute not found',404);const s=String(q.q||'').trim().toLowerCase();return D.fees.filter(f=>f.institute_id===q.instituteId).map(f=>{const st=D.students.find(x=>x.id===f.student_id);return{...f,student_name:st.name,admission_no:st.admission_no,class_name:st.class_name,section:st.section,institute_name:inst(q.instituteId).name}}).filter(f=>(!s||[f.student_name,f.admission_no,String(f.receipt_no)].some(v=>String(v||'').toLowerCase().includes(s)))&&(!q.from||day(f.received_at)>=q.from)&&(!q.to||day(f.received_at)<=q.to)).sort((a,b)=>b.received_at.localeCompare(a.received_at)).slice(0,5000).map(withAlloc)});
route('GET','/api/fees/:id',(b,id)=>{const f=D.fees.find(x=>x.id===id),i=f&&inst(f.institute_id);if(!i)E('Receipt not found',404);const s=D.students.find(x=>x.id===f.student_id);return withAlloc({...f,student_name:s.name,admission_no:s.admission_no,class_name:s.class_name,section:s.section,guardian:s.guardian,student_phone:s.phone,institute_name:i.name,logo_url:i.logo_url,address:i.address,institute_phone:i.phone,institute_email:i.email})});
route('GET','/api/student-history/:id',(b,id)=>{const s=stu(id);if(!s)E('Student not found',404);const it=summary(id);return{student:s,items:it,fees:D.fees.filter(f=>f.student_id===id).sort((a,b)=>b.received_at.localeCompare(a.received_at)).map(withAlloc),paid:sum(it,'paid'),total_fee:sum(it,'assigned_amount'),balance:sum(it,'balance')}});
route('GET','/api/student-statement/:id',(b,id)=>{const s=stu(id);if(!s)E('Student not found',404);const it=summary(id);return{student:s,items:it,total_fee:sum(it,'assigned_amount'),paid:sum(it,'paid'),balance:sum(it,'balance')}});
route('GET','/api/dashboard',(b,q)=>{if(!inst(q.instituteId))E('Institute not found',404);const id=q.instituteId,fs=D.fees.filter(f=>f.institute_id===id),td=day(now()),act=D.students.filter(s=>s.institute_id===id&&s.active);return{total:sum(fs,'amount'),today:sum(fs.filter(f=>day(f.received_at)===td),'amount'),students:act.length,pending:Math.max(0,act.reduce((t,s)=>t+sum(summary(s.id),'balance'),0))}});
route('GET','/api/reports/collection',(b,q)=>{if(!inst(q.instituteId))E('Institute not found',404);const fr=q.from||'2000-01-01',to=q.to||'2999-12-31',fs=D.fees.filter(f=>f.institute_id===q.instituteId&&day(f.received_at)>=fr&&day(f.received_at)<=to),m={};fs.forEach(f=>{const d=day(f.received_at);(m[d]=m[d]||{day:d,entries:0,total:0});m[d].entries++;m[d].total+=num(f.amount)});const ids=new Set(fs.map(f=>f.id)),bt={};D.alloc.filter(a=>ids.has(a.fee_id)).forEach(a=>{bt[a.fee_type_id]=(bt[a.fee_type_id]||0)+num(a.amount)});return{rows:Object.values(m).sort((a,b)=>b.day.localeCompare(a.day)),totals:{entries:fs.length,total:sum(fs,'amount')},byType:Object.entries(bt).map(([k,v])=>({fee_type_name:D.fee_types.find(x=>x.id===k).name,total:v})).sort((a,b)=>b.total-a.total)}});
const adm=()=>{if(!['SUPER_ADMIN','OWNER'].includes(session.role))E('Forbidden',403)};
route('GET','/api/owner-users',()=>{adm();return D.users.filter(u=>u.owner_id===owner()).map(({password_hash,...u})=>u)});
route('POST','/api/owner-users',async b=>{adm();if(!b.phone||!b.name||!b.password)E('Name, mobile and password required');if(D.users.some(u=>u.phone===b.phone))E('Mobile already exists');const id=uid();D.users.push({id,owner_id:owner(),phone:b.phone,email:b.email||null,name:b.name,password_hash:await hash(b.password),role:b.role||'STAFF',active:1,created_at:now()});return{ok:true,id}});
route('GET','/api/activity',()=>{adm();const us=new Map(D.users.filter(u=>u.owner_id===owner()).map(u=>[u.id,u]));return D.activity.filter(a=>us.has(a.user_id)).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,500).map(a=>({...a,user_name:us.get(a.user_id).name,phone:us.get(a.user_id).phone}))});
/* Backup / restore (moves data between phone and computer) */
G.ffExport=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(D)],{type:'application/json'}));a.download='feeflow-backup-'+day(now())+'.json';a.click()};
G.ffImport=async f=>{const d=JSON.parse(await f.text());if(!d.users||!d.students)throw Error('Invalid backup file');D=d;T.forEach(t=>D[t]=D[t]||[]);await save();localStorage.removeItem('ff_session');location.reload()};
G.localApi=async function(url,opt={}){await(ready=ready||load());const u=new URL(url,'http://x'),m=(opt.method||'GET').toUpperCase(),q=Object.fromEntries(u.searchParams);let body={};try{body=JSON.parse(opt.body||'{}')}catch(e){}
 for(const[rm,re,fn,pub]of R){const x=re.exec(u.pathname);if(rm===m&&x){try{if(!pub&&!session)E('Login required',401);const r=await fn(body,x[1]!==undefined?x[1]:q,q);if(m!=='GET')await save();return r}catch(e){if(e&&e.status){const er=Error(e.message);er.status=e.status;throw er}throw e}}}
 throw Error('Not found')};
})(typeof window!=='undefined'?window:globalThis);
